apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-web-app
  labels:
    app: hadoop-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-web-app
  template:
    metadata:
      labels:
        app: hadoop-web-app
    spec:
      containers:
      - name: hadoop-web-app
        image: evnp/hadoop
        resources:
          requests:
            memory: "1G"
            cpu: 1

---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-web-app
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: hadoop-web-app
